#!/usr/bin/env bash
# Render deploy/egress/filter from deploy/policy/pi.network.yaml (allow: list).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
POLICY="${ROOT}/deploy/policy/pi.network.yaml"
OUT="${ROOT}/deploy/egress/filter"

if [[ ! -f "$POLICY" ]]; then
  echo "missing $POLICY" >&2
  exit 1
fi

{
  echo "## Generated by deploy/scripts/gen-egress-filter.sh — do not edit by hand."
  echo "## Source: deploy/policy/pi.network.yaml"
  # Minimal YAML: lines under `allow:` that start with `- `
  awk '
    /^allow:[[:space:]]*$/ { in_allow=1; next }
    /^[a-zA-Z0-9_]+:/ { in_allow=0 }
    in_allow && /^[[:space:]]*-[[:space:]]+/ {
      line=$0
      sub(/^[[:space:]]*-[[:space:]]+/, "", line)
      gsub(/^["'\'']|["'\'']$/, "", line)
      if (line != "" && line !~ /^#/) print line
    }
  ' "$POLICY"
} > "$OUT"

echo "wrote $OUT ($(grep -cv '^#' "$OUT" || true) entries)"
