#!/usr/bin/env bash
# Probe this box and write /etc/sbx-kit/floor.md (CLI overlay).
set -euo pipefail
sudo mkdir -p /etc/sbx-kit
{
  echo "# sbx-kit floor (this box; regenerated by the CLI overlay)"
  echo
  echo "Read /etc/sbx-kit/context.md for how to interpret this probe."
  echo
  if [ -f /etc/sbx-kit-agent ]; then
    echo "kind: custom"
    echo "layer: $(tr -d '[:space:]' < /etc/sbx-kit-agent)"
  else
    echo "kind: official"
  fi
  echo
  if [ -x /usr/local/bin/mise ] && [ -d /mise ]; then echo "mise: yes"; else echo "mise: no"; fi
  if command -v gh >/dev/null 2>&1; then echo "gh: yes"; else echo "gh: no"; fi
  if command -v npm >/dev/null 2>&1; then echo "npm: yes"; else echo "npm: no"; fi
  if command -v go >/dev/null 2>&1; then echo "go: yes"; else echo "go: no"; fi
} | sudo tee /etc/sbx-kit/floor.md >/dev/null
sudo chmod 644 /etc/sbx-kit/floor.md
